WebApplication12/Models/Question.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication12.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Question
    {
        public int q_id { get; set; }
        [Required(ErrorMessage = "This Field is Required.")]
        [Display(Name = "Question Statement")]
        [StringLength(300, MinimumLength = 3, ErrorMessage = "Max 300 characters, Minimum 3.")]
        public string statement { get; set; }
        [Required(ErrorMessage = "This Field is Required.")]
        [Display(Name = "Option 1")]
        [StringLength(300, MinimumLength = 3, ErrorMessage = "Max 300 characters, Minimum 3.")]
        public string op1 { get; set; }
        [Required(ErrorMessage = "This Field is Required.")]
        [Display(Name = "Option 2")]
        [StringLength(300, MinimumLength = 3, ErrorMessage = "Max 300 characters, Minimum 3.")]
        public string op2 { get; set; }
        [Required(ErrorMessage = "This Field is Required.")]
        [Display(Name = "Option 3")]
        [StringLength(300, MinimumLength = 3, ErrorMessage = "Max 300 characters, Minimum 3.")]
        public string op3 { get; set; }
        [Required(ErrorMessage = "This Field is Required.")]
        [Display(Name = "Option 4")]
        [StringLength(300, MinimumLength = 3, ErrorMessage = "Max 300 characters, Minimum 3.")]
        public string op4 { get; set; }
        [Required(ErrorMessage = "This Field is Required.")]
        [Display(Name = "Correct option number")]
        public int answer { get; set; }
        public int test_id { get; set; }
    
        public virtual Test Test { get; set; }
    }
}

WebApplication12/Controllers/QuestionController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication12.Models;

namespace WebApplication12.Controllers
{
    public class QuestionController : Controller
    {
        private McqsDatabaseEntities db = new McqsDatabaseEntities();

        // GET: /Question/
        public ActionResult Index()
        {
            var questions = db.Questions.Include(q => q.Test);
            return View(questions.ToList());
        }

        // GET: /Question/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Question question = db.Questions.Find(id);
            if (question == null)
            {
                return HttpNotFound();
            }
            return View(question);
        }

        // GET: /Question/Create
        public ActionResult Create()
        {
            ViewBag.test_id = new SelectList(db.Tests, "test_id", "name");
            return View();
        }

        // POST: /Question/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="q_id,statement,op1,op2,op3,op4,answer,test_id")] Question question)
        {
            if (ModelState.IsValid)
            {
                db.Questions.Add(question);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.test_id = new SelectList(db.Tests, "test_id", "name", question.test_id);
            return View(question);
        }

        // GET: /Question/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Question question = db.Questions.Find(id);
            if (question == null)
            {
                return HttpNotFound();
            }
            ViewBag.test_id = new SelectList(db.Tests, "test_id", "name", question.test_id);
            return View(question);
        }

        // POST: /Question/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="q_id,statement,op1,op2,op3,op4,answer,test_id")] Question question)
        {
            if (ModelState.IsValid)
            {
                db.Entry(question).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.test_id = new SelectList(db.Tests, "test_id", "name", question.test_id);
            return View(question);
        }

        // GET: /Question/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Question question = db.Questions.Find(id);
            if (question == null)
            {
                return HttpNotFound();
            }
            return View(question);
        }

        // POST: /Question/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Question question = db.Questions.Find(id);
            db.Questions.Remove(question);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebApplication12/Controllers/TeacherAccountController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication12.Models;
using Microsoft.AspNet.Identity;
using System.Web.Security;

namespace WebApplication12.Controllers
{
    [Authorize]
    public class TeacherAccountController : Controller
    {
        private McqsDatabaseEntities db = new McqsDatabaseEntities();
        private int t_id = 1;
        private int test_id = 1;
        
        //------------------------------------------------------------Index
        [AllowAnonymous]
        //public void create()
        //{
        //    var check = db.Teachers.Where(t => t.username == User.Identity.Name).ToList();
        //    if (check.Count() == 0)
        //    {
        //        Teacher teacher = new Teacher();
        //        teacher.username = User.Identity.Name;
        //        teacher.password = null;
        //        teacher.name = null;
        //        teacher.email = null;
        //        db.Teachers.Add(teacher);
        //        db.SaveChanges();
        //    }
        //}
        public ActionResult Index()
        {
            //create();
            var students = db.Students.Where(s => s.t_id == t_id);
            var tests = db.Tests.Where(t => t.t_id == t_id);
            var model = new StudentTestViewModel { students = students.ToList(), tests = tests.ToList() };
            return View(model);
        }
        //------------------------------------------------------------ViewTests
        public ActionResult ViewTests(Test test)
        {
            test.t_id = t_id;
            if (test.name != null)
            {
                if (ModelState.IsValid)
                {
                    db.Tests.Add(test);
                    db.SaveChanges();
                }    
            }
            var tests = db.Tests.Where(t => t.t_id == t_id).ToList();

            return PartialView("ViewTests",tests);
        }
        //------------------------------------------------------------CreateTest
        public ActionResult CreateTest()
        {
            return View();
        }

        //------------------------------------------------------------ManageQuestions
        public ActionResult ManageQuestions(int? id)
        {
            //this is where i will set id in session of which test is being edit
            return View();
        }
        //------------------------------------------------------------Questions
        public ActionResult Questions(Question question)
        {
            question.test_id = test_id;
            if (question.statement != null)
            {
                if (ModelState.IsValid)
                {
                    db.Questions.Add(question);
                    db.SaveChanges();
                }
            }
            var questions = db.Questions.Where(q => q.test_id == test_id).ToList();
            return PartialView("Questions", questions);
        }
        //------------------------------------------------------------DeleteQuestion
        public ActionResult DeleteQuestion(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Question question = db.Questions.Find(id);
            if (question == null)
            {
                return HttpNotFound();
            }
            return View(question);
        }

        [HttpPost, ActionName("DeleteQuestion")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Question question = db.Questions.Find(id);
            db.Questions.Remove(question);
            db.SaveChanges();
            return RedirectToAction("ManageQuestions");
        }
        //------------------------------------------------------------EditQuestion
        public ActionResult EditQuestion(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Question question = db.Questions.Find(id);
            if (question == null)
            {
                return HttpNotFound();
            }
            ViewBag.test_id = new SelectList(db.Tests, "test_id", "name", question.test_id);
            return View(question);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditQuestion([Bind(Include = "q_id,statement,op1,op2,op3,op4,answer,test_id")] Question question)
        {
            if (ModelState.IsValid)
            {
                db.Entry(question).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("ManageQuestions");
            }
            ViewBag.test_id = new SelectList(db.Tests, "test_id", "name", question.test_id);
            return View(question);
        }
        //------------------------------------------------------------QuestionDetails
        public ActionResult QuestionDetails(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Question question = db.Questions.Find(id);
            if (question == null)
            {
                return HttpNotFound();
            }
            return View(question);
        }
        //------------------------------------------------------------ViewStudent
        public ActionResult ViewStudents(Student student)
        {
            student.t_id = t_id;
            if (student.password!=null)
            {
                if (ModelState.IsValid)
                {
                    db.Students.Add(student);
                    db.SaveChanges();
                }    
            }
            
            var students = db.Students.Where(s => s.t_id == t_id).ToList();
            return PartialView("ViewStudents", students);
        }
        //------------------------------------------------------------AddStudent
        public ActionResult AddStudent()
        {
            return View();
        }
        //------------------------------------------------------------TestDetails
        public ActionResult TestDetails(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Test test = db.Tests.Find(id);
            if (test == null)
            {
                return HttpNotFound();
            }
            var questions = db.Questions.Where(q => q.test_id == test.test_id);
            var model = new TestQuestionViewModel { questions = questions, test = test };
            return View(model);
        }
        //------------------------------------------------------------DeleteTest
        public ActionResult TestDelete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Test test = db.Tests.Find(id);
            if (test == null)
            {
                return HttpNotFound();
            }
            var questions = db.Questions.Where(q => q.test_id == test.test_id);
            var model = new TestQuestionViewModel { test = test, questions = questions };
            return View(model);
        }

        [HttpPost, ActionName("TestDelete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed5(int id)
        {
            Test test = db.Tests.Find(id);
            db.Tests.Remove(test);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        
        //------------------------------------------------------------EditTest
        public ActionResult EditTest(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Test test = db.Tests.Find(id);
            if (test == null)
            {
                return HttpNotFound();
            }
            ViewBag.t_id = new SelectList(db.Teachers, "t_id", "username", test.t_id);
            return View(test);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditTest([Bind(Include = "test_id,name,totalquestions,duaration")] Test test)
        {
            test.t_id = t_id;
            if (ModelState.IsValid)
            {
                db.Entry(test).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.t_id = new SelectList(db.Teachers, "t_id", "username", test.t_id);
            return View(test);
        }
        //------------------------------------------------------------DeleteStudent
        public ActionResult DeleteStudent(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Student student = db.Students.Find(id);
            if (student == null)
            {
                return HttpNotFound();
            }
            return View(student);
        }

        [HttpPost, ActionName("DeleteStudent")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed1(int id)
        {
            Student student = db.Students.Find(id);
            db.Students.Remove(student);
            db.SaveChanges();
            return RedirectToAction("AddStudent");
        }
        //------------------------------------------------------------StudentDetails
        public ActionResult StudentDetails(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Student student = db.Students.Find(id);

WebApplication12/Views/TeacherAccount/CreateTest.cshtml
@model WebApplication12.Models.Test
@{
    ViewBag.Title = "CreateTest";
}
<script src="~/Scripts/jquery-1.10.2.js"></script>
<script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>

<div class="container body-content" id="Result">


</div>
<h3>Add New</h3>
@using (Ajax.BeginForm("ViewTests", "TeacherAccount", null, new AjaxOptions
{
    HttpMethod = "POST",
    UpdateTargetId = "Result"
}
))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.name, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name)
                @Html.ValidationMessageFor(model => model.name)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.totalquestions, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.totalquestions)
                @Html.ValidationMessageFor(model => model.totalquestions)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.duaration, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.duaration)
                @Html.ValidationMessageFor(model => model.duaration)
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
    
    
    
    
    <script>
        $(document).ready(function () {
            $.ajax({
                url: "@Url.Action("ViewTests","TeacherAccount")",
                success: function (data, textStatus, XMLHttpRequest) {SetData(data);}
            });
            function SetData(data) {
                $("#Result").html(data);
            }
        });
    </script>
}


@*@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.name, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name)
                @Html.ValidationMessageFor(model => model.name)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.totalquestions, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.totalquestions)
                @Html.ValidationMessageFor(model => model.totalquestions)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.duaration, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.duaration)
                @Html.ValidationMessageFor(model => model.duaration)
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}*@

WebApplication12/Views/TeacherAccount/DeleteQuestion.cshtml
@model WebApplication12.Models.Question

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Question</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.statement)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.statement)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.op1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.op1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.op2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.op2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.op3)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.op3)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.op4)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.op4)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.answer)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.answer)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Test.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Test.name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "ManageQuestions", new { id = Model.test_id })
        </div>
    }
</div>

WebApplication12/Views/TeacherAccount/DeleteStudent.cshtml
@model WebApplication12.Models.Student
@{
    ViewBag.Title = "DeleteStudent";
}

<h2>DeleteStudent</h2>


<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Student</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.rollno)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.rollno)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.password)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "AddStudent")
        </div>
    }
</div>

WebApplication12/Views/TeacherAccount/EditQuestion.cshtml
@model WebApplication12.Models.Question

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Question</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.q_id)

        <div class="form-group">
            @Html.LabelFor(model => model.statement, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.statement)
                @Html.ValidationMessageFor(model => model.statement)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.op1, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.op1)
                @Html.ValidationMessageFor(model => model.op1)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.op2, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.op2)
                @Html.ValidationMessageFor(model => model.op2)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.op3, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.op3)
                @Html.ValidationMessageFor(model => model.op3)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.op4, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.op4)
                @Html.ValidationMessageFor(model => model.op4)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.answer, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.answer)
                @Html.ValidationMessageFor(model => model.answer)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "ManageQuestions", new { id = Model.test_id})
</div>

WebApplication12/Views/TeacherAccount/EditStudent.cshtml
@model WebApplication12.Models.Student
@{
    ViewBag.Title = "EditStudent";
}

<h2>EditStudent</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Student</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.s_id)

        <div class="form-group">
            @Html.LabelFor(model => model.rollno, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.rollno)
                @Html.ValidationMessageFor(model => model.rollno)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.password, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.password)
                @Html.ValidationMessageFor(model => model.password)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "AddStudent")
</div>

WebApplication12/Views/TeacherAccount/EditTest.cshtml
@model WebApplication12.Models.Test
@{
    ViewBag.Title = "EditTest";
}

<h2>EditTest</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Test</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.test_id)

        <div class="form-group">
            @Html.LabelFor(model => model.name, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name)
                @Html.ValidationMessageFor(model => model.name)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.totalquestions, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.totalquestions)
                @Html.ValidationMessageFor(model => model.totalquestions)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.duaration, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.duaration)
                @Html.ValidationMessageFor(model => model.duaration)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "CreateTest")
</div>

WebApplication12/Views/TeacherAccount/QuestionDetails.cshtml
@model WebApplication12.Models.Question

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Question</h4>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.statement)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.statement)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.op1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.op1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.op2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.op2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.op3)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.op3)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.op4)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.op4)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.answer)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.answer)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Test.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Test.name)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "EditQuestion", new { id = Model.q_id }) |
    @Html.ActionLink("Back to List", "ManageQuestions", new { id = Model.test_id })
</p>

WebApplication12/Views/TeacherAccount/Questions.cshtml
@model IEnumerable<WebApplication12.Models.Question>
@{
    ViewBag.Title = "questions";
}


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.statement)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.op1)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.op2)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.op3)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.op4)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.answer)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Test.name)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.statement)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.op1)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.op2)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.op3)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.op4)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.answer)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Test.name)
            </td>
            <td>
                @Html.ActionLink("Edit", "EditQuestion", new { id = item.q_id }) |
                @Html.ActionLink("Details", "QuestionDetails", new { id = item.q_id }) |
                @Html.ActionLink("Delete", "DeleteQuestion", new { id = item.q_id })
            </td>
        </tr>
    }

</table>